longitude: -71.1681156
latitude: 42.8836989
sunrise_offset: 60
sunset_offset: 45
open_pin: 20
close_pin: 26
api_server:
  enabled: true
  host: 0.0.0.0
  port: 8080
actuator_specs:
  stroke: 100
  duty_cycle: .25
  speed: 4